/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package NuevaGUI;

import Clases.Sucursal;
import Lista.Nodo;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author SONY
 */
public class Agregarsuc extends javax.swing.JFrame {

    String fecha;
    /**
     * Creates new form Agregarsuc
     */
    public Agregarsuc() {
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/imagenes/imagen2.png"));
        JLabel fondo= new JLabel(); 
        fondo.setIcon(uno); 
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agregar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        mes = new javax.swing.JComboBox();
        año = new javax.swing.JComboBox();
        ubicacion = new javax.swing.JTextField();
        nombresuc = new javax.swing.JTextField();
        clavesuc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        dia = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ALTAS SUCURSALES");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        agregar.setText("AGREGAR");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        agregar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                agregarKeyPressed(evt);
            }
        });

        cancelar.setText("CANCELAR");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel1.setText("CLAVE SUCURSAL");

        jLabel2.setText("NOMBRE SUCURSAL");

        jLabel3.setText("UBICACIÓN");

        jLabel4.setText("FECHA DE INICIO");

        mes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SEPTIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE" }));
        mes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mesMouseClicked(evt);
            }
        });
        mes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mesKeyPressed(evt);
            }
        });

        año.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014" }));
        año.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                añoMouseClicked(evt);
            }
        });
        año.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                añoKeyPressed(evt);
            }
        });

        ubicacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ubicacionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ubicacionKeyTyped(evt);
            }
        });

        nombresuc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombresucKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombresucKeyTyped(evt);
            }
        });

        clavesuc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                clavesucMousePressed(evt);
            }
        });
        clavesuc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                clavesucKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                clavesucKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("DATOS SUCURSAL");

        dia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        dia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                diaMouseClicked(evt);
            }
        });
        dia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                diaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout PanelLayout = new javax.swing.GroupLayout(Panel);
        Panel.setLayout(PanelLayout);
        PanelLayout.setHorizontalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelLayout.createSequentialGroup()
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(clavesuc, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombresuc, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(PanelLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel5)))
                .addContainerGap())
        );
        PanelLayout.setVerticalGroup(
            PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(clavesuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombresuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ubicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(mes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(agregar)
                        .addGap(80, 80, 80)
                        .addComponent(cancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelar)
                    .addComponent(agregar))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void agregar()
    {
        fecha=dia.getSelectedItem().toString()+"/"+mes.getSelectedItem().toString()+"/"+año.getSelectedItem().toString();
        Sucursal suc=new Sucursal(nombresuc.getText(),fecha,ubicacion.getText());
        Nodo nodsuc=new Nodo(suc,clavesuc.getText());
        BuscaFranq.aux1.setOtro(Principal.lista.insertar(nodsuc, BuscaFranq.aux1.getOtro()));
        JOptionPane.showMessageDialog(this, "AGREGADO","INFORMATIVO",JOptionPane.INFORMATION_MESSAGE);
        Control.contsuc++;
        limpiar();
        int op=JOptionPane.showConfirmDialog(this, "¿DESEA AGREGAR OTRA SUCURSAL?", "AGREGAR SUCURSAL", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if(JOptionPane.OK_OPTION!=op)
        {
            this.hide();
        }
    }
    private void limpiar()
    {
        clavesuc.setText("");
        nombresuc.setText("");
        ubicacion.setText("");
        nombresuc.setEnabled(false);
        ubicacion.setEnabled(false);
        dia.setEnabled(false);
        mes.setEnabled(false);
        año.setEnabled(false);
        agregar.setEnabled(false);
    }
    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
        agregar();
    }//GEN-LAST:event_agregarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        nombresuc.setEnabled(false);
        ubicacion.setEnabled(false);
        dia.setEnabled(false);
        mes.setEnabled(false);
        año.setEnabled(false);
        agregar.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        limpiar();
        int op=JOptionPane.showConfirmDialog(this, "SEGURO QUE DESEA CANCELAR", "CONFIRMA", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(JOptionPane.OK_OPTION==op)
        {
            this.hide();
        }
        else
        {
            clavesuc.requestFocus();
        }
    }//GEN-LAST:event_cancelarActionPerformed

    private void clavesucKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clavesucKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()=='\n')
         {
             if(clavesuc.getText().length()>0)
             {
                 if (clavesuc.getText().charAt(0) != 'S') 
                 {
                     clavesuc.setText("S" + clavesuc.getText());
                 }
                 nombresuc.setEnabled(true);
                 nombresuc.requestFocus();
             }
             else
             {
                JOptionPane.showMessageDialog(this, "CAMPO VACIO", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
             }
             
         }
    }//GEN-LAST:event_clavesucKeyPressed

    private void nombresucKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombresucKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()=='\n')
         {
             if(nombresuc.getText().length()>0)
             {
                 nombresuc.setText(nombresuc.getText().toUpperCase());
                 ubicacion.setEnabled(true);
                 ubicacion.requestFocus();
             }
             else
             {
                JOptionPane.showMessageDialog(this, "CAMPO VACIO", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
             }
             
         }
    }//GEN-LAST:event_nombresucKeyPressed

    private void ubicacionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ubicacionKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()=='\n')
         {
             if(ubicacion.getText().length()>0)
             {
                 ubicacion.setText(ubicacion.getText().toUpperCase());
                 dia.setEnabled(true);
                 dia.requestFocus();
             }
             else
             {
                JOptionPane.showMessageDialog(this, "CAMPO VACIO", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
             }
             
         }
    }//GEN-LAST:event_ubicacionKeyPressed

    private void diaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_diaMouseClicked
        // TODO add your handling code here:
            mes.setEnabled(true);
            mes.requestFocus();
    }//GEN-LAST:event_diaMouseClicked

    private void mesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mesMouseClicked
        // TODO add your handling code here:
            año.setEnabled(true);
            año.requestFocus();
    }//GEN-LAST:event_mesMouseClicked

    private void añoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_añoMouseClicked
        // TODO add your handling code here:
            agregar.setEnabled(true);
            agregar.requestFocus();
    }//GEN-LAST:event_añoMouseClicked

    private void diaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_diaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()=='\n')
         {
             mes.setEnabled(true);
             mes.requestFocus();
         }
    }//GEN-LAST:event_diaKeyPressed

    private void mesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mesKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()=='\n')
         {
             año.setEnabled(true);
             año.requestFocus();
        }
    }//GEN-LAST:event_mesKeyPressed

    private void añoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_añoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()=='\n')
         {
             agregar.setEnabled(true);
             agregar.requestFocus();
        }
    }//GEN-LAST:event_añoKeyPressed

    private void clavesucKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clavesucKeyTyped
        // TODO add your handling code here:
        Control.contarcadena(clavesuc.getText(), 5);
        char c = evt.getKeyChar();
        if(!Control.band)
        {
            evt.consume();
            clavesuc.setText("");
            nombresuc.setEnabled(false);
        }
        if (((c >= 33 && c<=47) || c>=58) && c != 'S') 
        {
            JOptionPane.showMessageDialog(this, "SOLO VALORES NUMÉRICOS", "ERROR", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_clavesucKeyTyped

    private void nombresucKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombresucKeyTyped
        // TODO add your handling code here:
        Control.contarcadena(nombresuc.getText(), 25);
        if(!Control.band)
        {
            evt.consume();
            nombresuc.setText("");
            ubicacion.setEnabled(false);
        }
        
    }//GEN-LAST:event_nombresucKeyTyped

    private void ubicacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ubicacionKeyTyped
        // TODO add your handling code here:
        Control.contarcadena(ubicacion.getText(), 25);
        if(!Control.band)
        {
            evt.consume();
            ubicacion.setText("");
            ubicacion.setEnabled(false);
        }
    }//GEN-LAST:event_ubicacionKeyTyped

    private void clavesucMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clavesucMousePressed
        // TODO add your handling code here:
        if(!clavesuc.getText().isEmpty())
        {
          if (clavesuc.getText().charAt(0) == 'S') 
          {
              String aux = clavesuc.getText().substring(1, clavesuc.getText().length());
              clavesuc.setText(aux);
          }
        }  
    }//GEN-LAST:event_clavesucMousePressed

    private void agregarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_agregarKeyPressed
        // TODO add your handling code here:
        agregar();
    }//GEN-LAST:event_agregarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregarsuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregarsuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregarsuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregarsuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregarsuc().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel;
    private javax.swing.JButton agregar;
    private javax.swing.JComboBox año;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField clavesuc;
    private javax.swing.JComboBox dia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox mes;
    private javax.swing.JTextField nombresuc;
    private javax.swing.JTextField ubicacion;
    // End of variables declaration//GEN-END:variables
}
