/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package NuevaGUI;

import Clases.Auto;
import Lista.Nodo;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author SONY
 */
public class Agregarauto extends javax.swing.JFrame {

    String fecha1,fecha2;
    /**
     * Creates new form Agregarauto
     */
    public Agregarauto() {
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/imagenes/imagen2.png"));
        JLabel fondo= new JLabel(); 
        fondo.setIcon(uno); 
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        claveauto = new javax.swing.JTextField();
        nomprop = new javax.swing.JTextField();
        marca = new javax.swing.JTextField();
        modelo = new javax.swing.JTextField();
        matricula = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tiposervicio = new javax.swing.JTextField();
        costo = new javax.swing.JTextField();
        agregar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        mesinicio = new javax.swing.JComboBox();
        mesfinal = new javax.swing.JComboBox();
        añoinicial = new javax.swing.JComboBox();
        añofinal = new javax.swing.JComboBox();
        diainicio = new javax.swing.JComboBox();
        diafin = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ALTAS AUTOS");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("CARACTERÍSTICAS DEL AUTO");

        jLabel3.setText("CLAVE AUTO");

        jLabel4.setText("NOMBRE PROPIETARIO");

        jLabel5.setText("MARCA");

        jLabel6.setText("MODELO");

        jLabel7.setText("MATRICULA");

        claveauto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                claveautoMousePressed(evt);
            }
        });
        claveauto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                claveautoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                claveautoKeyTyped(evt);
            }
        });

        nomprop.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nompropKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nompropKeyTyped(evt);
            }
        });

        marca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                marcaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                marcaKeyTyped(evt);
            }
        });

        modelo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                modeloKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                modeloKeyTyped(evt);
            }
        });

        matricula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                matriculaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                matriculaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(modelo, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                    .addComponent(matricula)
                    .addComponent(nomprop)
                    .addComponent(claveauto)
                    .addComponent(marca))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(claveauto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nomprop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(modelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(matricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("SERVICIO");

        jLabel8.setText("TIPO DERVICIO");

        jLabel10.setText("COSTO");

        tiposervicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tiposervicioKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tiposervicioKeyTyped(evt);
            }
        });

        costo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                costoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                costoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tiposervicio)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(costo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(135, 135, 135))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel2)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tiposervicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(costo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        agregar.setText("AGREGAR");
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });
        agregar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                agregarKeyPressed(evt);
            }
        });

        cancelar.setText("CANCELAR");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("FECHA DE ENTRADA-SALIDA");

        jLabel9.setText("FECHA DE INICIO");

        jLabel11.setText("FECHA FINAL");

        mesinicio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SEPTIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE" }));
        mesinicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mesinicioKeyPressed(evt);
            }
        });

        mesfinal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ENERO", "FEBRERO", "MARZO", "ABRIL", "MAYO", "JUNIO", "JULIO", "AGOSTO", "SEPTIEMBRE", "OCTUBRE", "NOVIEMBRE", "DICIEMBRE" }));
        mesfinal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                mesfinalKeyPressed(evt);
            }
        });

        añoinicial.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014" }));
        añoinicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                añoinicialKeyPressed(evt);
            }
        });

        añofinal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014" }));
        añofinal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                añofinalKeyPressed(evt);
            }
        });

        diainicio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        diainicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                diainicioKeyPressed(evt);
            }
        });

        diafin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        diafin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                diafinKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel9))
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(diainicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diafin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mesinicio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mesfinal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(añoinicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(añofinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addGap(106, 106, 106))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(mesinicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(añoinicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diainicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(mesfinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(añofinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diafin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(283, 283, 283)
                .addComponent(agregar)
                .addGap(60, 60, 60)
                .addComponent(cancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(153, 153, 153))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregar)
                    .addComponent(cancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void agregar()
    {
        fecha1=diainicio.getSelectedItem().toString()+"/"+mesinicio.getSelectedItem().toString()+"/"+añoinicial.getSelectedItem().toString();
        fecha2=diafin.getSelectedItem().toString()+"/"+mesfinal.getSelectedItem().toString()+"/"+añofinal.getSelectedItem().toString();
        Auto aut=new Auto(nomprop.getText(),fecha1,matricula.getText(),marca.getText(),modelo.getText(),Integer.parseInt(costo.getText()),tiposervicio.getText(),fecha2);
        Nodo nodaut=new Nodo(aut, claveauto.getText());
        BuscaSuc.aux2.setOtro(Principal.lista.insertar(nodaut, BuscaSuc.aux2.getOtro()));
        JOptionPane.showMessageDialog(this, "AGREGADO","INFORMATIVO",JOptionPane.INFORMATION_MESSAGE);
        Control.contauto++;
        limpiar();
        int op=JOptionPane.showConfirmDialog(this, "¿DESEA AGREGAR OTRO AUTOMOVIL?", "AGREGAR AUTO", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if(JOptionPane.OK_OPTION!=op)
        {
            this.hide();
        }
    }
    private void limpiar()
    {
        claveauto.setText("");
        nomprop.setText("");
        marca.setText("");
        modelo.setText("");
        matricula.setText("");
        tiposervicio.setText("");
        costo.setText("");
        nomprop.setEnabled(false);
        marca.setEnabled(false);
        modelo.setEnabled(false);
        matricula.setEnabled(false);
        diainicio.setEnabled(false);
        mesinicio.setEnabled(false);
        añoinicial.setEnabled(false);
        diafin.setEnabled(false);
        mesfinal.setEnabled(false);
        añofinal.setEnabled(false);
        tiposervicio.setEnabled(false);
        costo.setEnabled(false);
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        nomprop.setEnabled(false);
        marca.setEnabled(false);
        modelo.setEnabled(false);
        matricula.setEnabled(false);
        diainicio.setEnabled(false);
        mesinicio.setEnabled(false);
        añoinicial.setEnabled(false);
        diafin.setEnabled(false);
        mesfinal.setEnabled(false);
        añofinal.setEnabled(false);
        tiposervicio.setEnabled(false);
        costo.setEnabled(false);
        agregar.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        limpiar();
        int op=JOptionPane.showConfirmDialog(this, "SEGURO QUE DESEA CANCELAR", "CONFIRMAR", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(JOptionPane.OK_OPTION==op)
        {
            this.hide();
        }
        else
        {
            claveauto.requestFocus();
        }
    }//GEN-LAST:event_cancelarActionPerformed

    private void claveautoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_claveautoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()=='\n')
         {
             if(claveauto.getText().length()>0)
             {
                 if(claveauto.getText().charAt(0)!='A')
                 {
                    claveauto.setText("A"+ claveauto.getText());
                 }
                 nomprop.setEnabled(true);
                 nomprop.requestFocus();
             }
             else
             {
                JOptionPane.showMessageDialog(this, "CAMPO VACIO", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
             }
             
         }
    }//GEN-LAST:event_claveautoKeyPressed

    private void nompropKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nompropKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()=='\n')
         {
             if(nomprop.getText().length()>0)
             {
                 nomprop.setText(nomprop.getText().toUpperCase());
                 marca.setEnabled(true);
                 marca.requestFocus();
             }
             else
             {
                JOptionPane.showMessageDialog(this, "CAMPO VACIO", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
             }
         }
    }//GEN-LAST:event_nompropKeyPressed

    private void marcaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_marcaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()=='\n')
         {
             if(marca.getText().length()>0)
             {
                 marca.setText(marca.getText().toUpperCase());
                 modelo.setEnabled(true);
                 modelo.requestFocus();
             }
             else
             {
                JOptionPane.showMessageDialog(this, "CAMPO VACIO", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
             }
             
         }
    }//GEN-LAST:event_marcaKeyPressed

    private void modeloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_modeloKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()=='\n')
         {
             if(modelo.getText().length()>0)
             {
                 modelo.setText(modelo.getText().toUpperCase());
                 matricula.setEnabled(true);
                 matricula.requestFocus();
             }
             else
             {
                JOptionPane.showMessageDialog(this, "CAMPO VACIO", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
             }
             
         }
    }//GEN-LAST:event_modeloKeyPressed

    private void matriculaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_matriculaKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()=='\n')
         {
             if(matricula.getText().length()>0)
             {
                 matricula.setText(matricula.getText().toUpperCase());
                 diainicio.setEnabled(true);
                 diainicio.requestFocus();
             }
             else
             {
                JOptionPane.showMessageDialog(this, "CAMPO VACIO", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
             }
         }
    }//GEN-LAST:event_matriculaKeyPressed

    private void diainicioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_diainicioKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()=='\n')
         {
             mesinicio.setEnabled(true);
             mesinicio.requestFocus();
         }
    }//GEN-LAST:event_diainicioKeyPressed

    private void diafinKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_diafinKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()=='\n')
         {
             mesfinal.setEnabled(true);
             mesfinal.requestFocus();
         }
    }//GEN-LAST:event_diafinKeyPressed

    private void mesinicioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mesinicioKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()=='\n')
         {
             añoinicial.setEnabled(true);
             añoinicial.requestFocus();
         }
    }//GEN-LAST:event_mesinicioKeyPressed

    private void añoinicialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_añoinicialKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()=='\n')
         {
             diafin.setEnabled(true);
             diafin.requestFocus();
         }
    }//GEN-LAST:event_añoinicialKeyPressed

    private void mesfinalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mesfinalKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()=='\n')
         {
             añofinal.setEnabled(true);
             añofinal.requestFocus();
         }
    }//GEN-LAST:event_mesfinalKeyPressed

    private void añofinalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_añofinalKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()=='\n')
         {
             tiposervicio.setEnabled(true);
             tiposervicio.requestFocus();
         }
    }//GEN-LAST:event_añofinalKeyPressed

    private void tiposervicioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tiposervicioKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()=='\n')
         {
             if(tiposervicio.getText().length()>0)
             {
                 tiposervicio.setText(tiposervicio.getText().toUpperCase());
                 costo.setEnabled(true);
                 costo.requestFocus();
             }
             else
             {
                JOptionPane.showMessageDialog(this, "CAMPO VACIO", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
             }
             
         }
    }//GEN-LAST:event_tiposervicioKeyPressed

    private void costoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_costoKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyChar()=='\n')
         {
             if(costo.getText().length()>0)
             {
                 agregar.setEnabled(true);
                 agregar.requestFocus();
             }
             else
             {
                JOptionPane.showMessageDialog(this, "CAMPO VACIO", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
             }
             
         }
    }//GEN-LAST:event_costoKeyPressed

    private void claveautoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_claveautoKeyTyped
        // TODO add your handling code here:
        Control.contarcadena(claveauto.getText(), 5);
        char c = evt.getKeyChar();
        if(!Control.band)
        {
            evt.consume();
            claveauto.setText("");
            nomprop.setEnabled(false);
        }
        if (((c >= 33 && c<=47) || c>=58) && c != 'S') 
        {
            JOptionPane.showMessageDialog(this, "SOLO VALORES NUMÉRICOS", "ERROR", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_claveautoKeyTyped

    private void nompropKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nompropKeyTyped
        // TODO add your handling code here:
        Control.contarcadena(nomprop.getText(), 40);
        if(!Control.band)
        {
            evt.consume();
            nomprop.setText("");
            marca.setEnabled(false);
        }
    }//GEN-LAST:event_nompropKeyTyped

    private void marcaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_marcaKeyTyped
        // TODO add your handling code here:
        Control.contarcadena(marca.getText(), 15);
        if(!Control.band)
        {
            evt.consume();
            marca.setText("");
            modelo.setEnabled(false);
        }
    }//GEN-LAST:event_marcaKeyTyped

    private void modeloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_modeloKeyTyped
        // TODO add your handling code here:
        Control.contarcadena(modelo.getText(), 15);
        if(!Control.band)
        {
            evt.consume();
            modelo.setText("");
            matricula.setEnabled(false);
        }
    }//GEN-LAST:event_modeloKeyTyped

    private void matriculaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_matriculaKeyTyped
        // TODO add your handling code here:
        Control.contarcadena(matricula.getText(), 10);
        if(!Control.band)
        {
            evt.consume();
            matricula.setText("");
            diainicio.setEnabled(false);
        }
    }//GEN-LAST:event_matriculaKeyTyped

    private void tiposervicioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tiposervicioKeyTyped
        // TODO add your handling code here:
        Control.contarcadena(tiposervicio.getText(), 50);
        if(!Control.band)
        {
            evt.consume();
            tiposervicio.setText("");
            costo.setEnabled(false);
        }
    }//GEN-LAST:event_tiposervicioKeyTyped

    private void costoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_costoKeyTyped
        // TODO add your handling code here:
        Control.contarcadena(costo.getText(), 10);
        if(!Control.band)
        {
            evt.consume();
            costo.setText("");
            agregar.setEnabled(false);
        }
        char c = evt.getKeyChar();
        if((c >= 'a' && c <='z' && c!='A'))
        {
            JOptionPane.showMessageDialog(this, "SOLO VALORES NUMÉRICOS", "ERROR", JOptionPane.WARNING_MESSAGE);
            evt.consume();
        }
    }//GEN-LAST:event_costoKeyTyped

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        // TODO add your handling code here:
        agregar();
    }//GEN-LAST:event_agregarActionPerformed

    private void claveautoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_claveautoMousePressed
        // TODO add your handling code here:
        if(!claveauto.getText().isEmpty())
        {
          if (claveauto.getText().charAt(0) == 'S') 
          {
              String aux = claveauto.getText().substring(1, claveauto.getText().length());
              claveauto.setText(aux);
          }
        }  
    }//GEN-LAST:event_claveautoMousePressed

    private void agregarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_agregarKeyPressed
        // TODO add your handling code here:
        agregar();
    }//GEN-LAST:event_agregarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregarauto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregarauto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregarauto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregarauto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregarauto().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JComboBox añofinal;
    private javax.swing.JComboBox añoinicial;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField claveauto;
    private javax.swing.JTextField costo;
    private javax.swing.JComboBox diafin;
    private javax.swing.JComboBox diainicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField marca;
    private javax.swing.JTextField matricula;
    private javax.swing.JComboBox mesfinal;
    private javax.swing.JComboBox mesinicio;
    private javax.swing.JTextField modelo;
    private javax.swing.JTextField nomprop;
    private javax.swing.JTextField tiposervicio;
    // End of variables declaration//GEN-END:variables
}
