/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package NuevaGUI;

import Lista.ListaDobleC;
import Lista.Nodo;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author SONY
 */
public class BuscaSuc extends javax.swing.JFrame {

    /**
     * Creates new form BuscaSuc
     */
    static Nodo aux2;
    Nodo auxe;
    Nodo aux=BuscaFranq.aux1.getOtro();
    boolean band=true;
    public BuscaSuc() {
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/imagenes/imagen2.png"));
        JLabel fondo= new JLabel(); 
        fondo.setIcon(uno); 
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        suc = new javax.swing.JComboBox();
        aceptar = new javax.swing.JButton();
        mensaje2 = new javax.swing.JLabel();
        mensaje1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BUSCAR SUCURSALES");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SELECCIONE UNA SUCURSAL");

        aceptar.setText("ACEPTAR");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        mensaje2.setForeground(new java.awt.Color(255, 255, 255));
        mensaje2.setText("*SUCURSALES CON AUTOMOVILES");

        mensaje1.setForeground(new java.awt.Color(255, 255, 255));
        mensaje1.setText("*SUCURSALES QUE PUEDEN ELIMINARSE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mensaje2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(suc, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mensaje1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(aceptar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(suc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(aceptar)
                .addGap(18, 18, 18)
                .addComponent(mensaje1)
                .addGap(18, 18, 18)
                .addComponent(mensaje2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        // TODO add your handling code here:
        aux2=ListaDobleC.buscar(suc.getSelectedItem().toString(), BuscaFranq.aux1.getOtro());
        switch(Principal.id)
        {
            case 1:
                new Agregarauto().setVisible(true);
                this.hide();
                break;
            case 2:
                if(Informacion.select!=2)
                {
                    if(band)
                    {
                        new BuscaAuto().setVisible(true);
                        this.hide();
                    }
                    else
                    {
                       this.hide();
                    }
                    
                }
                else
                {
                    Contenido.imprimir(aux2);
                    new Contenido().setVisible(true);
                    this.hide();
                }
                break;
            case 3:
                if(Informacion.select!=2)
                {
                    new BuscaAuto().setVisible(true);
                    this.hide();
                }
                else
                {
                    if(aux2==BuscaFranq.aux1.getOtro())
                    {
                        BuscaFranq.aux1.setOtro(aux2.getSiguiente());
                        auxe=Principal.lista.elimina(aux2.getClave(), BuscaFranq.aux1.getOtro().getAtras());
                        
                    }
                    else
                    {
                        auxe=Principal.lista.elimina(aux2.getClave(), BuscaFranq.aux1.getOtro());
                    }
                    if(auxe.getClave().equals(BuscaFranq.aux1.getOtro().getClave()))
                    {
                        BuscaFranq.aux1.setOtro(null);
                    }
                    Control.contsuc--;
                    JOptionPane.showMessageDialog(this, "ELIMINADO SATISFACTORIAMENTE ", "ELIMINA", JOptionPane.INFORMATION_MESSAGE);
                    Contenido.imprimir(auxe);
                    new Contenido().setVisible(true);
                    this.hide();
                }
                
        }
    }//GEN-LAST:event_aceptarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        mensaje1.setVisible(false);
        mensaje2.setVisible(false);
        this.suc.removeAllItems();
        switch(Principal.id)
        {
            case 1:
                do
                {
                    String cves=aux.getClave();
                    this.suc.addItem(cves);
                    aux=aux.getSiguiente();
                }while(aux!=BuscaFranq.aux1.getOtro());
                break;
            case 2:
                if(Informacion.select!=2)
                {
                    mensaje2.setVisible(true);
                    do
                    {
                      if(aux.getOtro()!=null)
                      {
                          String cves=aux.getClave();
                          this.suc.addItem(cves);
                      }
                      aux=aux.getSiguiente();
                    }while(aux!=BuscaFranq.aux1.getOtro());
                }
                else
                {
                    do
                    {
                        String cvef=aux.getClave();
                        this.suc.addItem(cvef);
                        aux=aux.getSiguiente();
                    }while(aux!=BuscaFranq.aux1.getOtro());
                }
                break;
            case 3:
                if(Informacion.select!=2)
                {
                    mensaje2.setVisible(true);
                    do
                    {
                      if(aux.getOtro()!=null)
                      {
                          String cves=aux.getClave();
                          this.suc.addItem(cves);
                      }
                      aux=aux.getSiguiente();
                    }while(aux!=BuscaFranq.aux1.getOtro());
                }
                else
                {
                    mensaje1.setVisible(true);
                    do
                    {
                        if(aux.getOtro()==null)
                        {
                            String cvef=aux.getClave();
                            this.suc.addItem(cvef);
                        }
                        aux=aux.getSiguiente();
                    }while(aux!=BuscaFranq.aux1.getOtro());
                }
                break;
        }
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        switch(Principal.id)
        {
            case 2:
                if(suc.getSelectedItem()==null)
                {
                    band=false;
                    JOptionPane.showMessageDialog(this, "LISTA DE SUCURSALES SIN AUTOMOVILES", "DIALOGO", JOptionPane.WARNING_MESSAGE);
                    int op=JOptionPane.showConfirmDialog(this, "¿DESEA AGREGAR UN AUTO?", "PREGUNTA", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                    if(JOptionPane.OK_OPTION!=op)
                    {
                          this.hide();
                    }
                    else
                    {
                         new BuscaFranq().setVisible(true);
                         this.hide();
                    }
                }
                else
                {
                    formWindowActivated(evt);
                }
                break;
            case 3:
                if(suc.getSelectedItem()==null)
                {
                    band=false;
                    JOptionPane.showMessageDialog(this, "IMPOSIBLE ELIMINAR SUCURSAL (CONTIENE DATOS)", "DIALOGO", JOptionPane.WARNING_MESSAGE);
                    this.hide();
                }
                else
                {
                    formWindowActivated(evt);
                }
                break;
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscaSuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscaSuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscaSuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscaSuc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscaSuc().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel mensaje1;
    private javax.swing.JLabel mensaje2;
    private javax.swing.JComboBox suc;
    // End of variables declaration//GEN-END:variables
}
