/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package NuevaGUI;

import Lista.ListaDobleC;
import Lista.Nodo;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author SONY
 */
public class BuscaFranq extends javax.swing.JFrame {

    static Nodo aux1;
    Nodo auxe;
    Nodo aux=Principal.lista.getR();
    /**
     * Creates new form BuscaFranq
     */
  
   
    public BuscaFranq() 
    {
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno=new ImageIcon(this.getClass().getResource("/imagenes/imagen2.png"));
        JLabel fondo= new JLabel(); 
        fondo.setIcon(uno); 
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
        initComponents();
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        franq = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        aceptar = new javax.swing.JButton();
        mensaje2 = new javax.swing.JLabel();
        mensaje1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BUSCAR FRANQUICIAS");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        franq.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                franqMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SELECCIONE UNA FRANQUICIA");

        aceptar.setText("ACEPTAR");
        aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarActionPerformed(evt);
            }
        });

        mensaje2.setForeground(new java.awt.Color(255, 255, 255));
        mensaje2.setText("*FRANQUICIAS QUE CUANTAN CON SUCURSALES");

        mensaje1.setForeground(new java.awt.Color(255, 255, 255));
        mensaje1.setText("*FRANQUICIAS QUE SE PUEDEN ELIMINAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mensaje2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mensaje1)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(franq, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(aceptar)))
                        .addGap(67, 67, 67))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(franq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(aceptar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(mensaje1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mensaje2))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarActionPerformed
        // TODO add your handling code here:
        aux1= ListaDobleC.buscar(franq.getSelectedItem().toString(), ListaDobleC.r);
        switch(Principal.id)
        {
            case 1:
                if(Informacion.select==2)
                {
                    new Agregarsuc().setVisible(true);
                    this.hide();
                }
                else
                {
                    new BuscaSuc().setVisible(true);
                    this.hide();
                }
                break;
            case 2:
                if(Informacion.select!=1)
                {
                    new BuscaSuc().setVisible(true);
                    this.hide();
                } 
                else
                {
                    Contenido.imprimir(aux1);
                    new Contenido().setVisible(true);
                    this.hide();
                }
                break;
            case 3:
                if(Informacion.select!=1)
                {
                    new BuscaSuc().setVisible(true);
                    this.hide();
                }
                else
                {
                    if(aux1==ListaDobleC.r)
                    {
                        ListaDobleC.r=aux1.getSiguiente();
                        auxe=Principal.lista.elimina(aux1.getClave(), ListaDobleC.r.getAtras());
                    }
                    else
                    {
                        auxe=Principal.lista.elimina(aux1.getClave(), ListaDobleC.r);
                    }
                    
                    if(auxe.getClave().equals(ListaDobleC.r.getClave()))
                    {
                        ListaDobleC.r=null;
                    }
                        Control.contfranq--;
                        JOptionPane.showMessageDialog(this, "ELIMINADO SATISFACTORIAMENTE ", "ELIMINA", JOptionPane.INFORMATION_MESSAGE);
                        Contenido.imprimir(auxe);
                        new Contenido().setVisible(true);
                        this.hide();
                }
                break;
            case 4:
                new ModificarFranquicia().setVisible(true);
                    this.hide();
                
                break;
                
        }
    }//GEN-LAST:event_aceptarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
      
    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        if(Principal.id==3)
        {
            if(franq.getSelectedItem()==null)
                {
                    JOptionPane.showMessageDialog(this, "TODAS LAS FRANQUICIAS CONTIENEN DATOS... IMPOSIBLE ELIMINAR", "DIALOGO", JOptionPane.WARNING_MESSAGE);
                    this.hide();
                }
                else
                {
                    formWindowActivated(evt);
                }
        }
    }//GEN-LAST:event_formWindowOpened

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        mensaje1.setVisible(false);
        mensaje2.setVisible(false);
        this.franq.removeAllItems();
        switch(Principal.id)
        {
            case 1:
                if(Informacion.select==3)
                {
                    mensaje2.setVisible(true);
                    do
                    {
                      if(aux.getOtro()!=null)
                      {
                          String cvef=aux.getClave();
                          this.franq.addItem(cvef);
                      }
                      aux=aux.getSiguiente();
                    }while(aux!=ListaDobleC.r);
                }
                else
                {
                    do
                    {
                        String cvef=aux.getClave();
                        this.franq.addItem(cvef);
                        aux=aux.getSiguiente();
                    }while(aux!=ListaDobleC.r);
                }
                break;
                
            case 2:
                if(Informacion.select!=1)
                {
                    mensaje2.setVisible(true);
                    do
                    {
                      if(aux.getOtro()!=null)
                      {
                          String cvef=aux.getClave();
                          this.franq.addItem(cvef);
                      }
                      aux=aux.getSiguiente();
                    }while(aux!=ListaDobleC.r);
                }
                else
                {
                    do
                    {
                        String cvef=aux.getClave();
                        this.franq.addItem(cvef);
                        aux=aux.getSiguiente();
                    }while(aux!=ListaDobleC.r);
                }
                break;
            case 3:
                if(Informacion.select!=1)
                {
                    mensaje2.setVisible(true);
                    do
                    {
                      if(aux.getOtro()!=null)
                      {
                          String cvef=aux.getClave();
                          this.franq.addItem(cvef);
                      }
                      aux=aux.getSiguiente();
                    }while(aux!=ListaDobleC.r);
                }
                else
                {
                    mensaje1.setVisible(true);
                    do
                    {
                        if(aux.getOtro()==null)
                        {
                            String cvef=aux.getClave();
                            this.franq.addItem(cvef);
                        }
                        aux=aux.getSiguiente();
                    }while(aux!=ListaDobleC.r);
                }
                break;
            case 4:
                do
                    {
                        if(aux.getOtro()==null)
                        {
                            String cvef=aux.getClave();
                            this.franq.addItem(cvef);
                        }
                        aux=aux.getSiguiente();
                    }while(aux!=ListaDobleC.r);
                break;
        }
    }//GEN-LAST:event_formWindowActivated

    private void franqMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_franqMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_franqMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscaFranq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscaFranq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscaFranq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscaFranq.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscaFranq().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptar;
    protected javax.swing.JComboBox franq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel mensaje1;
    private javax.swing.JLabel mensaje2;
    // End of variables declaration//GEN-END:variables
}
